package const

WINDOW_WIDTH :: 800
WINDOW_HEIGHT :: 600

ZOOM :: 6.0

TILE_SIZE :: 12

CHECKER_SIZE :: TILE_SIZE * 2
CHECKER_WIDTH :: WINDOW_WIDTH / CHECKER_SIZE
CHECKER_HEIGHT :: WINDOW_HEIGHT / CHECKER_SIZE
