package const

WINDOW_WIDTH :: 792
WINDOW_HEIGHT :: 504

ZOOM :: 6.0

TILE_SIZE :: 12

DEFAULT_LEVEL_WIDTH :: 11
DEFAULT_LEVEL_HEIGHT :: 7

CHECKER_SIZE :: TILE_SIZE * 2
CHECKER_WIDTH :: WINDOW_WIDTH / CHECKER_SIZE
CHECKER_HEIGHT :: WINDOW_HEIGHT / CHECKER_SIZE
